version: "3"
services:
  go-std:
    build:
      context: ./frameworks/go-std
    container_name: go-std
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - GOMAXPROCS=$BENCH_WORKERS

  go-fasthttp:
    build:
      context: ./frameworks/go-fasthttp
    container_name: go-fasthttp
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - GOMAXPROCS=$BENCH_WORKERS

  node-express:
    build:
      context: ./frameworks/node-express
    container_name: node-express
    environment:
    - BENCH_WORKERS=$BENCH_WORKERS

  python-flask:
    build:
      context: ./frameworks/python-flask
    container_name: python-flask
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS

  python-fastapi:
    build:
      context: ./frameworks/python-fastapi
    container_name: python-fastapi
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS

  openresty:
    build:
      context: ./frameworks/openresty
    container_name: openresty
    ports:
      - "8080:8080"
    volumes:
      - ./frameworks/openresty/conf:/opt/openresty/conf
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS

  rust-warp:
    build:
      context: ./frameworks/rust-warp
    container_name: rust-warp
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS

  rust-actix:
    build:
      context: ./frameworks/rust-actix
    container_name: rust-actix
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
