version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$BENCH_DB_PASSWORD
      - POSTGRES_USER=$BENCH_DB_USER
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  go-std:
    build:
      context: ./frameworks/go-std
    container_name: go-std
    depends_on:
      - postgres
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD
      - GOMAXPROCS=$BENCH_WORKERS

  go-fasthttp:
    build:
      context: ./frameworks/go-fasthttp
    container_name: go-fasthttp
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD
      - GOMAXPROCS=$BENCH_WORKERS

  node-express:
    build:
      context: ./frameworks/node-express
    container_name: node-express
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  python-flask:
    build:
      context: ./frameworks/python-flask
    container_name: python-flask
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  python-fastapi:
    build:
      context: ./frameworks/python-fastapi
    container_name: python-fastapi
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  openresty:
    build:
      context: ./frameworks/openresty
    container_name: openresty
    ports:
      - "8080:8080"
    volumes:
      - ./frameworks/openresty/conf:/opt/openresty/conf
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  rust-warp:
    build:
      context: ./frameworks/rust-warp
    container_name: rust-warp
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  rust-actix:
    build:
      context: ./frameworks/rust-actix
    container_name: rust-actix
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  dotnetcore-webapi:
    build:
      context: ./frameworks/dotnetcore-webapi
    container_name: dotnetcore-webapi
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD

  ruby-sinatra:
    build:
      context: ./frameworks/ruby-sinatra
    container_name: ruby-sinatra
    environment:
      - BENCH_WORKERS=$BENCH_WORKERS
      - BENCH_DB_HOST=postgres
      - BENCH_DB_PORT=5432
      - BENCH_DB_USER=$BENCH_DB_USER
      - BENCH_DB_PASSWORD=$BENCH_DB_PASSWORD
